version: '3.7'
services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=relayer
      - POSTGRES_PASSWORD=relayer
      - POSTGRES_DB=relayer
    volumes:
      - ./data/postgres:/var/lib/postgresql/data