// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: admin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RelayerAdminClient is the client API for RelayerAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayerAdminClient interface {
	CreateCustomToken(ctx context.Context, in *CreateCustomTokenRequest, opts ...grpc.CallOption) (*CreateCustomTokenResponse, error)
}

type relayerAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayerAdminClient(cc grpc.ClientConnInterface) RelayerAdminClient {
	return &relayerAdminClient{cc}
}

func (c *relayerAdminClient) CreateCustomToken(ctx context.Context, in *CreateCustomTokenRequest, opts ...grpc.CallOption) (*CreateCustomTokenResponse, error) {
	out := new(CreateCustomTokenResponse)
	err := c.cc.Invoke(ctx, "/relayer.RelayerAdmin/CreateCustomToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayerAdminServer is the server API for RelayerAdmin service.
// All implementations must embed UnimplementedRelayerAdminServer
// for forward compatibility
type RelayerAdminServer interface {
	CreateCustomToken(context.Context, *CreateCustomTokenRequest) (*CreateCustomTokenResponse, error)
	mustEmbedUnimplementedRelayerAdminServer()
}

// UnimplementedRelayerAdminServer must be embedded to have forward compatible implementations.
type UnimplementedRelayerAdminServer struct {
}

func (UnimplementedRelayerAdminServer) CreateCustomToken(context.Context, *CreateCustomTokenRequest) (*CreateCustomTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomToken not implemented")
}
func (UnimplementedRelayerAdminServer) mustEmbedUnimplementedRelayerAdminServer() {}

// UnsafeRelayerAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayerAdminServer will
// result in compilation errors.
type UnsafeRelayerAdminServer interface {
	mustEmbedUnimplementedRelayerAdminServer()
}

func RegisterRelayerAdminServer(s grpc.ServiceRegistrar, srv RelayerAdminServer) {
	s.RegisterService(&RelayerAdmin_ServiceDesc, srv)
}

func _RelayerAdmin_CreateCustomToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayerAdminServer).CreateCustomToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relayer.RelayerAdmin/CreateCustomToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayerAdminServer).CreateCustomToken(ctx, req.(*CreateCustomTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayerAdmin_ServiceDesc is the grpc.ServiceDesc for RelayerAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayerAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relayer.RelayerAdmin",
	HandlerType: (*RelayerAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomToken",
			Handler:    _RelayerAdmin_CreateCustomToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
